version: '3.5'

services:

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo-data:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
        - 5672:5672
        - 15672:15672

  # web-go:
  #   build: .
  #   volumes:
  #     - .:/www/
  #   command: bash -c "
  #     ./srv/wait-for.sh rabbitmq:5672 --
  #     go build -o web-docker-go
  #     && ./web-docker-go"
  #   ports:
  #    - 8088:8088
  #   depends_on:
  #     - rabbitmq
  #     - mongo
  #     - mongo-express
  
  frontend:
    build: frontend
    ports:
      - 8089:80