CREATE TABLE apps (
    id integer PRIMARY KEY,
    name VARCHAR(256) UNIQUE NOT NULL,
    key VARCHAR(256) UNIQUE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);